### ISSUE TITLE
Update README with links to open notebooks in google colab

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/Python-Deep-Learning-Legacy#7]
For folks that have no access to datahub, add links to colab notebooks in the README

**Comment by aculich** [comment]
Also take a look at @emgrabow9 [CSSTP TensorFlow notebook](https://github.com/dlab-berkeley/Computational-Social-Science-Training-Program/blob/e0c12c2a4202b5684ed6aafe81145d108b8c063f/5%20Natural%20Language%20Processing/5-5%20Neural%20Nets%20for%20NLP/5-5%20Deep%20Learning%20and%20Tensorflow%20%5BStudent%5D.ipynb) since that may have the google colab setup we need.
